# Configuration file for Ryzen Mobile Limiter (ryzenm-limit)
# The daemon reads from this file to apply/reapply these values
# temp-limit specifies the maximum temperature that the APU should operate at (in degrees celsius)
# stapm-limit manages long-term peak power limit of the APU, which can assist in overheating prevention
# fast-limit manages short-term peak power limit of the APU, which can be used for brief bursts of performance
# slow-limit manages average power limit of the APU
#
# Example configuration:
# temp-limit=90
# stapm-limit=25
# fast-limit=35
# slow-limit=30
#
temp-limit=88
#fast-limit=50
#sdfg
#stapm-limit=50
stapm-limit=60
fast-limit=75
slow-limit=36sf
slow-limit=60
slow-limit=fhu
